spring.application.name=purchase-currency-converter

spring.datasource.url=jdbc:h2:mem:purchasedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

treasury.api.base-url=https://api.fiscaldata.treasury.gov/services/api/fiscal_service